- apt: upgrade=dist update_cache=yes

- name: Basic utils
  apt: name={{ item }} 
  with_items:
  - youtube-dl
  - nmap
  - openssh-server
  - curl
  - emacs
  - git
  - git-core
  - links
  - lynx
  - mercurial
  - mosh
  - nmap
  - npm
  - whois
  - screen
  - exiv2
  - wipe
  - build-essential
  - texlive-base
  - texlive-fonts-extra
  - texlive-fonts-recommended
  - texlive-latex-extra
  - texlive-latex-recommended
  - texlive-publishers
  - texlive-xetex
  - pdftk
  - wireless-tools
  - pump
  - xfonts-base
  - xfonts-100dpi
  - xfonts-75dpi
  - cython
  - ipython
  - libxml2-dev
  - libxslt1-dev
  - python-boto
  - python-bson
  - python-dev
  - python-matplotlib
  - python-numpy
  - python-pandas
  - python-pip
  - python-scipy
  - python-setuptools
  - python-sklearn
  - virtualenvwrapper
  - libjpeg-dev
  - python-opencv
